### ISSUE TITLE
Inflight transaction can be voided more than once.

### ISSUE THREAD

**Issue by stkegoul** [blnkfinance/blnk#41]
Can send a "void" request for an inflight transaction more than once. The first request voids it as expected. 

But subsequent requests return a successful response with undefined values in the amount fields. See sample below:

![image](https://github.com/blnkledger/blnk/assets/24396019/948f4965-3f1b-4d48-82e8-33f351095d1e)

**Comment by jerry-enebeli** [comment]
thanks @stkegoul
